#+TITLE: smax

#+BEGIN_HTML
<a href="https://travis-ci.org/sdll/smax"><img src="https://travis-ci.org/sdll/smax.svg?branch=master"></a>
#+END_HTML

* Installation

** Windows users
Install git (http://git-scm.com/download/win). Open a git bash terminal. Run this command.

#+BEGIN_SRC sh
bash -c "$(curl -fsSL https://raw.githubusercontent.com/sdll/smax/master/install-smax-win.sh)"
#+END_SRC

There is an emacs binary in this repository for Windows. You should be able to run the scimax.sh command to launch scimax now.

** Mac users

Run the next command in your terminal in the location you want to install scimax. The command will make sure you have [[http://brew.sh][homebrew]], git, and emacs installed, and then will clone scimax and tell you how to use it. It will take some time to install. You need to install your own LaTeX and Python probably.

#+BEGIN_SRC sh
bash -c "$(curl -fsSL https://raw.githubusercontent.com/sdll/smax/master/install-smax-mac.sh)"
#+END_SRC

*** Alternative manual installation of smax for Mac users
Alternatively, you can install [[http://brew.sh][homebrew]] yourself, install git from http://git-scm.com/download/mac, build your emacs like this:

#+BEGIN_SRC sh
brew install emacs --with-gnutls --with-imagemagick --with-librsvg --with-x11 --use-git-head --HEAD --with-cocoa
#+END_SRC

After that, you can clone smax like this:

#+BEGIN_SRC sh
git clone https://github.com/sdll/smax.git
#+END_SRC

and launch emacs with:

#+BEGIN_SRC sh
emacs -q -l smax/init.el
#+END_SRC

** Linux users
Run this command. It checks for a git and emacs, but does not install them. You will have to use your package manager for that. You also need to install your own LaTeX and Python (and other languages you might want).

#+BEGIN_SRC sh
bash -c "$(curl -fsSL https://raw.githubusercontent.com/sdll/smax/master/install-smax-linux.sh)"
#+END_SRC
