(setq initial-buffer-choice "~/ORG/map.org")
(save-place-mode 1)
(setq vc-follow-symlinks nil)
(require 'init-haskell)
(require 'init-latex)
(require 'init-locales)
(require 'init-notes)
(require 'init-email)
(require 'init-yas)
(require 'init-utils)
(require 'init-bookmarks)
(require 'init-blog)
(require 'init-c)
