(setq initial-buffer-choice "~/ORG/todo.org")
(save-place-mode 1)
(require 'init-haskell)
(require 'init-latex)
(require 'init-locales)
(require 'init-notes)
(require 'init-email)
(require 'init-yas)
(require 'init-utils)
(require 'init-bookmarks)
(require 'init-blog)
